version: '2.0'
services:
  workerL:
    #image: morse-stf:v0.3
    image: morsestf_test20210712
    #image: registry.cn-hangzhou.aliyuncs.com/dtunion/morseredis:v24
    ports:
      - 8886:8886
    cap_add:
      - ALL
    tty: true

    #stdin_open: true
    volumes:
    # - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
     - /Users/qizhi.zqz/projects/morse-stf/morse-stf/conf:/morse-stf/conf
    command:
        python3 /morse-stf/stensorflow/engine/start_server.py --player=workerL  --config_file=/morse-stf/conf/config_docker.json
        #wondershaper eth0 10240 10240
  workerR:
    image: morsestf_test20210712
    ports:
    - 8887:8887
    cap_add:
      - ALL
    tty: true
    #stdin_open: true
    volumes:
    # - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    - /Users/qizhi.zqz/projects/morse-stf/morse-stf/conf:/morse-stf/conf
    command:
#      - /bin/bash
#      - -c
#      - |
        python3 /morse-stf/stensorflow/engine/start_server.py --player=workerR  --config_file=/morse-stf/conf/config_docker.json
        #wondershaper eth0 10240 10240
  RS:
    image: morsestf_test20210712
    ports:
      - 8888:8888
    cap_add:
      - ALL
    tty: true
    #stdin_open: true
    volumes:
    #- /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    #- /Users/qizhi.zqz/projects/TFE/tf-encrypted/examples/test_on_morse_datas/data:/morse-stf/data
    - /Users/qizhi.zqz/projects/morse-stf/morse-stf/conf:/morse-stf/conf
    command: python3 /morse-stf/stensorflow/engine/start_server.py --player=RS  --config_file=/morse-stf/conf/config_docker.json


#networks:
#  counter-net:
#
#volumes:
#  counter-vol:

#docker exec -it  xxx  wondershaper eth0 10240 10240